version: "3"
services:
  db:
    image: postgres:13
    container_name: spotify_pg
    environment:
      POSTGRES_USER: alan
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: spotifydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
